[build]
  publish = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/ui"
  to = "/.netlify/functions/twikoo/ui"
  status = 200
  force = true

[[redirects]]
  from = "/ui/*"
  to = "/.netlify/functions/twikoo/ui/:splat"
  status = 200
  force = true
